import ctypes

def array(pylist:list, fmt:str) -> ctypes.c_void_p: ...
def tolist(pycapsule:ctypes.c_void_p, length:int, fmt:str) -> list: ...
def sizeof(length:int, fmt:str) -> int: ...
def getitem(pycapsule:ctypes.c_void_p, index:int) -> int: ...
def setitem(pycapsule:ctypes.c_void_p, index:int, value:int, fmt:str) -> None: ...
